# Generated by Django 2.1.4 on 2019-02-05 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RelationWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq', models.CharField(max_length=500, null=True, unique=True)),
                ('progress', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.UUIDField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('translate', models.CharField(max_length=60)),
                ('descriptions', models.CharField(max_length=300, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('category_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CategoryWord')),
            ],
        ),
        migrations.AddField(
            model_name='relationword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Word'),
        ),
    ]
