# Generated by Django 2.1.4 on 2019-02-05 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type_game', models.IntegerField()),
                ('col_rounds', models.IntegerField(null=True)),
                ('result', models.IntegerField(null=True)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('game_round', models.IntegerField()),
                ('result', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RelationWord')),
            ],
        ),
    ]
